config/routes.rb
Rails.application.routes.draw do

  
  root "static_pages#index", as: :home

  get "users" => "users#index"                 # shows all users
  get "signup" => "users#new", as: :signup   # signup form for new user
  post "users" => "users#create"               # creates new user when form is submitted
  get "users/:id" => "users#show", as: :user   # single user show page, shows profile

  get "login" => "sessions#new", as: :login
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy", as: :logout

  get "users/:id/projects" => "projects#index", as: :user_projects
  get "users/:id/projects/new" => "projects#new", as: :new_user_project
  post "users/:id/projects" => "projects#create", as: :user_projects_create
  get "users/:user_id/projects/:id" => "projects#show", as: :user_project
  get "users/:user_id/projects/:id/edit" => "projects#edit", as: :project_edit
  patch "users/:user_id/projects/:id" => "projects#update"
  delete "users/:user_id/projects/:id" => "projects#destroy"

  get "users/:user_id/projects/:id/milestones/new" => "milestones#new", as: :new_project_milestone
  post "users/:user_id/projects/:id" => "milestones#create", as: :project_milestones
  get "users/:user_id/projects/:project_id/milestones/:id" => "milestones#show", as: :project_milestone
  get "users/:user_id/projects/:project_id/milestones/:id/edit" => "milestones#edit", as: :milestone_edit
  patch "users/:user_id/projects/:project_id/milestones/:id"  => "milestones#update"
  delete "users/:user_id/projects/:project_id/milestones/:id" => "milestones#destroy"

  get "users/:user_id/projects/:id/milestones/:id/tasks/new" => "tasks#new", as: :new_task
  post "users/:user_id/projects/:id/milestones/:id" => "tasks#create", as: :tasks
  get "users/:user_id/projects/:id/milestones/:id/tasks/:id/edit" => "tasks#edit", as: :task_edit
  delete "users/:user_id/projects/:id/milestones/:id/tasks/:id" => "tasks#destroy"
  patch "tasks/:id" => "tasks#update"
  get "tasks/:id" => "tasks#show", as: :task

end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :project
  has_many :tasks

  def active_tasks
    self.tasks.where.not(completed: true)
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :milestones

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :milestone
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects

  attr_reader :password

  def password=(unencrypted_password)
    unless unencrypted_password.empty?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def authenticate(unencrypted_password)
    if BCrypt::Password.new(self.password_digest) == unencrypted_password
      return self
    else
      return false
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  include SessionsHelper

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController


  def index
    @project = Project.find(params[:id])
    @milestones = @project.milestones
  end

  def new
    @project = Project.find(params[:id])
    @milestone = @project.milestones.new
  end

  def show
    @milestone = Milestone.find(params[:id])
    @project = @milestone.project
    
    @tasks = @milestone.tasks.where.not(completed: true)
    @task = Task.new
  end

  def create
    @project = Project.find(params[:id])
    @milestone = @project.milestones.new(milestone_params)

    @milestone.save
    redirect_to user_project_path(@project.user, @project)
  end

  def edit
    @milestone = Milestone.find(params[:id])
    @project = @milestone.project
  end

  def update
    @milestone = Milestone.find(params[:id])
    @project = @milestone.project

    if @milestone.update(milestone_params)
      redirect_to project_milestone_path(current_user, @project, @milestone)
    else
      render :new
    end
  end

  def destroy
    @milestone = Milestone.find(params[:id])
    @project = @milestone.project
    @user = @project.user
    @milestone.destroy

    redirect_to user_project_path(@user, @project)
  end

  private
  def milestone_params
    params.require(:milestone).permit(:name)
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @user = User.find(params[:id])
    @projects = @user.projects
  end

  def new
    @user = User.find(params[:id])
    @project = @user.projects.new
  end

  def show
    @project = Project.find(params[:id])
    @user = @project.user

    @milestones = @project.milestones
    @milestone = Milestone.new
  end

  def create
    @user = User.find(params[:id])
    @project = @user.projects.new(project_params)

    @project.save
    redirect_to user_projects_path(@user)
  end

  def edit
    @project = Project.find(params[:id])
    @user = @project.user
  end 

  def update
    @project = Project.find(params[:id])
    @user = @project.user

    if @project.update(project_params)
      redirect_to user_project_path(@user, @project)
    else
      render :new
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to user_projects_path(@project.user)
  end


  private
  def project_params
    params.require(:project).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:login][:email])

    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id.to_s
      redirect_to user_path(user)
    else
      render :new
    end

  end

  def destroy
    session.delete(:user_id)
    redirect_to home_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @milestone = Milestone.find(params[:id])
    @tasks = @milestone.tasks
  end

  def new
    @milestone = Milestone.find(params[:id])
    @task = @milestone.tasks.new
  end

  def show
    @task = Task.find(params[:id])
    @milestone = @task.milestone

  end

  def create
    @milestone = Milestone.find(params[:id])
    @task = @milestone.tasks.new(task_params)
    @task.completed = false
    @project = @milestone.project

    @task.save
    redirect_to project_milestone_path(@project.user, @project, @milestone)
  end

  def edit
    @task = Task.find(params[:id])
    @milestone = @task.milestone
  end

  def update
    @task = Task.find(params[:id])
    @milestone = @task.milestone
    @project = @milestone.project

    @task.completed = true

    if @task.save
      redirect_to project_milestone_path(@project.user, @project, @milestone)
    else
      render :new
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @milestone = @task.milestone
    @project = @milestone.project
    @task.destroy

    redirect_to project_milestone_path(@project, @milestone)
  end


  private
  def task_params
    params.require(:task).permit(:description)
  end

end

app/controllers/users_controller.rb
 class UsersController < ApplicationController

  before_action :authenticate, only: [:show]
  before_action :correct_user, only: [:show]
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @project = Project.new
    @current_user = current_user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to home_path
    else
      render :new
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def authenticate
    redirect_to(login_path) if current_user.nil?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(home_path) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def logged_in?
    session[:user_id] != nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-custom">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="logo" href="#">TaskFlow</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

      <!-- Conditional links dependent on user being logged in or out -->
        <% if current_user != nil %>
          <li><%= link_to "#{current_user.name} Profile", user_path(current_user) %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <title><%= content_for?(:title) ? yield(:title) : "TaskFlow" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <%= render "layouts/navbar" %>
</header>

<div class="container-fluid">

  <%= yield %>
  
</div>

</body>
</html>

app/views/milestones/edit.html.erb
<div class="container">

  <div class="text-left page-header custom-page-header">
    <h1> <%= link_to "#{@milestone.name}", project_milestone_path %>
      <small>edit</small> 
    </h1>
  </div> 


  <%= form_for [@project, @milestone], url: project_milestone_path, method: "patch" do |f| %>
    <div class="col-xs-12 col-sm-6 col-md-4">

      <div class="form-group">
        <%= f.label :name, class: "control-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit 'Save', class: "btn btn-primary" %>
        <%= link_to "cancel", url_for(:back), class: "btn btn-secondary" %>
      </div>

    </div>
  <% end %>

</div>

app/views/milestones/new.html.erb
<div class="container">

  <div class="text-left page-header custom-page-header">
    <h1> <%= link_to "#{@project.name}", user_project_path(@project.user, @project) %>
      <small>new milestone</small> 
    </h1>
  </div>


  <%= form_for [@project,@milestone], url: project_milestones_path, method: "post" do |f| %>
    <div class="col-xs-12 col-sm-6 col-md-4">

      <div class="form-group">
        <%= f.label :name, class: "control-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit 'Save', class: "btn btn-primary" %>
        <%= link_to "cancel", url_for(:back), class: "btn btn-secondary" %>
      </div>

    </div>
  <% end %>

</div>

app/views/milestones/show.html.erb
<div class="container">


<!-- Start edit buttons for header object -->
  <div class="form-group">
    <%= link_to "Edit", milestone_edit_path(current_user, @project, @milestone), class: "btn-sm btn-primary" %>
    <%= link_to "Delete this Milestone", project_milestone_path(current_user, @project, @milestone), method: :delete, class: "btn-sm btn-primary" %>
  </div>
<!-- End edit buttons for header object -->


<!-- Start of Page Header -->
  <div class="text-left page-header custom-page-header">
    <h1> <%= link_to "#{@milestone.name}", user_project_path(@project.user, @project) %>
      <small>tasks</small> 
    </h1>
  </div> 
<!-- End of Page Header -->


  <div class="row">  

          <div class="col-sm-6 col-md-4 custom-column">
            <div class="text-center col-md-12 project">
              <p><%= "#{@milestone.name}" %></p>
            </div>

            <div class="col-md-12">
              <ul class="list-group">
                <% @tasks.each do |task| %>
                  <%= form_for(task, as: :task)  do |f| %>

                      <li class="list-group-item">
                            <div class="pull-left">
                              <%= task.description %>
                            </div>
                            <div class="text-right">
                              <%= f.submit "Done", class: "btn btn-primary btn-xs" %>
                            </div>
                      </li>

                  <% end %>
                <% end %>
              </ul>
            </div>
          </div>

          <div class="col-sm-6 col-md-4 col-md-offset-1">
            <h3 id="task-header">Add a new Task</h3>
            <%= form_for [@milestone, @task], url: tasks_path, method: "post" do |f| %>

                <div class="form-group">
                  <%= f.text_area :description, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.submit 'Save', class: "btn btn-primary" %>
                  <%= link_to "cancel", url_for(:back), class: "btn btn-secondary" %>
                </div>

            <% end %>
          </div>

  </div>

  <%= link_to "Back to the Project", user_project_path(current_user, @project) %>
</div>


<!-- OLD MILESTONE SHOW PAGE BELOW -->

app/views/projects/edit.html.erb
<div class="container">

  <div class="text-left page-header custom-page-header">
    <h1> <%= link_to "#{@project.name}", user_projects_path %>
      <small>edit</small> 
    </h1>
  </div>


  <%= form_for [@user,@project] do |f| %>
    <div class="col-xs-12 col-sm-6 col-md-4">

      <div class="form-group">
        <%= f.label :name, class: "control-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit 'Save', class: "btn btn-primary" %>
        <%= link_to "cancel", url_for(:back), class: "btn btn-secondary" %>
      </div>

    </div>
  <% end %>

</div>

app/views/projects/index.html.erb
<div class="container">

  <div class="text-left page-header custom-page-header">
    <h1><%= "#{current_user.name}'s Projects" %></h1>
  </div>

  <div class="row">  


      <% @projects.each do |project|%>
        <%= link_to user_project_path(project.user, project) do %>
          <div class="col-sm-4 col-md-3 custom-column">
            <div class="text-center col-md-12 project">
              <p><%= "#{project.name}" %></p>
            </div>
          </div>
        <% end %>
      <% end %>



  </div>


  <h3>Add a new Project</h3>

  <%= link_to "+ New Project", new_user_project_path, class: "btn btn-primary" %>

</div>

app/views/projects/new.html.erb
<div class="container">

  <div class="text-left page-header custom-page-header">
    <h1> <%= link_to "Projects", user_projects_path(@user) %>
      <small>new</small> 
    </h1>
  </div>


  <%= form_for [@user,@project] do |f| %>
    <div class="col-xs-12 col-sm-6 col-md-4">

      <div class="form-group">
        <%= f.label :name, class: "control-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit 'Save', class: "btn btn-primary" %>
        <%= link_to "cancel", url_for(:back), class: "btn btn-secondary" %>
      </div>

    </div>
  <% end %>

</div>

app/views/projects/show.html.erb
<div class="container">


<!-- Start edit buttons for header object -->
  <div class="form-group">
    <%= link_to "Edit", project_edit_path(@user, @project), class: "btn-sm btn-primary" %>
    <%= link_to "Delete this Project", user_project_path(@user, @project), method: :delete, class: "btn-sm btn-primary" %>
  </div>
<!-- End edit buttons for header object -->

<!-- Start of Page Header -->
  <div class="text-left page-header custom-page-header">

    <h1> <%= link_to "#{@project.name}", user_projects_path(@user) %>
      <small>milestones</small> 
    </h1>

  </div> 
<!-- End of Page Header -->


  <div class="row">  

      <% @milestones.each do |milestone|%>

          <div class="col-sm-4 col-md-3 custom-column">

            <%= link_to project_milestone_path(@user, @project, milestone) do %>
              <div class="text-center col-md-12 project">
                <p><%= "#{milestone.name}" %></p>
              </div>
            <% end %>

            <div class="col-md-12">
              <ul class="list-group">
                <% milestone.active_tasks.each do |task| %>
                  <%= form_for(task, as: :task)  do |f| %>

                      <li class="list-group-item">
                            <div class="pull-left">
                              <%= task.description %>
                            </div>
                            <div class="text-right">
                              <%= f.submit "Done", class: "btn btn-primary btn-xs" %>
                            </div>
                      </li>

                  <% end %>
                <% end %>
              </ul>
            </div>
          </div>

      <% end %>
  </div>


  <h3>Add a new Milestone</h3>

  <%= link_to "+ New Milestone", new_project_milestone_path, class: "btn btn-primary" %>

  <%= link_to "Back to my Projects", user_projects_path(@user) %>

</div>

app/views/static_pages/index.html.erb
<h1 class="text-center"> Welcome to TaskFlow</h1>

<div class="jumbotron">
  <h4 class="text-center">Organize your workflow and experience a better way to work.</h4>
</div>


  <%= link_to signup_path do %>
    <div class="btn btn-primary btn-success col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4 col-md-2 col-md-offset-5">
      <h4>Sign Up</h4>
    </div>
  <% end %>

app/views/tasks/new.html.erb
<h1>Create a Task</h1>

<%= form_for [@milestone, @task], url: tasks_path, method: "post" do |f| %>
  <div>
    <%= f.text_area :description %>
  </div>

  <%= f.submit "Save task" %>

<% end %>


<%= link_to "cancel", url_for(:back) %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |u| %>
    <li> <%= u.name %> </li>
  <% end %>
</ul>

app/views/users/login.html.erb
<h1>Log In</h1>

<%= form_for :login do |f| %>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.submit 'Log In' %>
  </div>
  
<% end %>

app/views/users/new.html.erb
<div class="container">

  <div class="text-center page-header custom-page-header"><h1> Sign Up </h1></div>


  <div class="container text-left my-form col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-12">

  <%= form_for @user do |f| %>

    <div class="form-group">
      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :email, class: "control-label" %>
      <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password, class: "control-label" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div>
      <%= f.submit 'Sign Up', class: "btn btn-primary" %>
      <%= link_to "cancel", home_path, class: "btn btn-secondary" %>
    </div>
    
  <% end %>

  </div>

</div>

app/views/users/show.html.erb
<div class="container">

  <div class="text-left page-header custom-page-header"><h1> Profile </h1></div>

  <%= link_to "Go to my Projects", user_projects_path %>

</div>